### ISSUE TITLE
Solution isn't guaranteed to be finite

### ISSUE THREAD

**Issue by bphillab** [msthil/Riddler-One-Small-Step-Solution#1]
The solution present has the issues of ties that you note which requires a reflip. This means that you can't guarantee a finite number of flips.

**Comment by msthil** [comment]
That is very true. Going to edit and try to rework to get the final, correct answer. Probably shouldn't post until I'm completely finished. Still a relative newbie. Thanks for the input.

**Comment by bphillab** [comment]
What? Nah, you're all good. What is git except to collaborate/share code?

Let me know if you need help. I had to use an ansatz to get this one.

**Comment by bphillab** [comment]
For this problem try making 4 flips work you can do this by noting that the probabilities are:

1   p^4
4 (1-p)p^3 
6 (1-p)^2 p^2
4 (1-p)^3 p
1  (1-p)^4

we can assign 2 cases to 2(1-p) p^3+ 3(1-p)^2p^2+2(1-p)^3p
And the remaining case is composed of the rest/

**Comment by msthil** [comment]
That was the general idea I was playing around with, but unfortunately, this one got away from me. Read the solution, and I'll try to use that to do some backwards problem solving on the code.  Thanks for the help.
